### ISSUE TITLE
小米 MI 4LTE-CT 安卓4.4.4 运行demo 报错

### ISSUE THREAD

**Issue by BensonMax** [Tencent/QT4A#15]
2019-02-14 14:22:20,088 INFO 9936 执行ADB命令耗时：0.075388956887
2019-02-14 14:22:20,088 DEBUG 9936 Run server sh: /data/local/tmp/qt4a/SpyHelper.sh: No such file or directory
2019-02-14 14:22:20,088 INFO 9936 adb 127.0.0.1:4adb4609 shell ps
2019-02-14 14:22:20,187 INFO 9936 执行ADB命令耗时：0.09904395269
2019-02-14 14:22:21,190 DEBUG 9936 [DeviceDriver] Server com.test.androidspy process created: False
2019-02-14 14:22:21,194 DEBUG 9936 server_opened (127.0.0.1, 15662) [Errno 10054] 
2019-02-14 14:22:21,194 INFO 9936 adb 127.0.0.1:4adb4609 forward tcp:15662 localabstract:com.test.androidspy
2019-02-14 14:22:21,198 INFO 9936 执行ADB命令耗时：0.00296476781769
2019-02-14 14:22:41,148 INFO 16224 log: --------- beginning of /dev/log/system not match pattern
2019-02-14 14:22:21,203 ERROR 9936 send '{"Cmd": "Hello", "Seq": 1}\n' error: [Errno 10054] 
Traceback (most recent call last):
  File "D:\Anaconda3\envs\Fauto\lib\site-packages\qt4a\androiddriver\clientsocket.py", line 168, in send_command
    result = self.send(data)
  File "D:\Anaconda3\envs\Fauto\lib\site-packages\qt4a\androiddriver\clientsocket.py", line 113, in send
    expect_len = self.recv(8)
  File "D:\Anaconda3\envs\Fauto\lib\site-packages\qt4a\androiddriver\clientsocket.py", line 100, in recv
    return self._sock.recv(buff_size)
error: [Errno 10054]

**Comment by hqlian007** [comment]
1. 请确认下[是否已成功安装QT4A测试桩](http://file.sng.com/browse/qta/htdocs/qt4a/lastest/testcase.html#id4_),
2. 如果是非root手机，请确认是否[已进行了重打包](http://file.sng.com/browse/qta/htdocs/qt4a/lastest/testcase.html#id6)

**Comment by BensonMax** [comment]
@hqlian007 谢谢回复。 demo 已实现。
