### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf5 in position 82: invalid start byte

### ISSUE THREAD

**Issue by lillian1234** [Tencent/QT4A#27]
============================================================
测试用例:HelloTest 所有者:Administrator 优先级:High 超时:5分钟
============================================================
----------------------------------------
步骤1: 1、登录Android demo
RESOURCE: acquire resource (res_type:android, res_group:None, condition:{}) successfully(OPPO A59s arm64-v8a Android 5.1)
ENVIRONMENT: 申请 Android 设备成功：OPPO A59s(LRLJ4H6599999999)
2019-05-09 15:55:40,410 123145489002496 thread Thread-2 exit
Traceback (most recent call last):
  File "/Users/wulixia/Library/Python/2.7/lib/python/site-packages/qt4a/androiddriver/util.py", line 531, in run
    return threading.Thread.run(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/wulixia/Library/Python/2.7/lib/python/site-packages/qt4a/androiddriver/adb.py", line 564, in _logcat_thread_func
    self.insert_logcat('%s(%d)' % (pid_dict.get(pid), pid), self._year, ret.group(1), ret.group(2), ret.group(5), ret.group(6), ret.group(4), ret.group(7))
  File "/Users/wulixia/Library/Python/2.7/lib/python/site-packages/qt4a/androiddriver/adb.py", line 461, in insert_logcat
    content))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf5 in position 82: invalid start byte

**Comment by drunkdream** [comment]
已增加异常捕获逻辑，请升级到`2.2.19`版本使用
