### ISSUE TITLE
device.connect_wifi('xxx', 'xxx')提示RuntimeError: java.lang.RuntimeException: ssid xxx not found

### ISSUE THREAD

**Issue by xyd113** [Tencent/QT4A#39]
Android设备：google Pixel arm64-v8a Android 7.1.1
出错代码行：device.connect_wifi('xxx', 'xxx')  # 'xxx'是马赛克
日志：
Traceback (most recent call last):
  File "/Users/Anker/qtaf_project/footestproj/footest/hello.py", line 48, in <module>
    HelloTest().debug_run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/testbase/testcase.py", line 518, in debug_run
    return runner.run(tests)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/testbase/runner.py", line 241, in run
    self.run_all_tests(self.load(target))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/testbase/runner.py", line 356, in run_all_tests
    passed = self.run_test(test)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/testbase/runner.py", line 290, in run_test
    result = runner.run(test, self.__report.get_testresult_factory())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/testbase/testcase.py", line 815, in run
    raise RuntimeError("用例执行线程异常：\n%s" % smart_text(self._error))
RuntimeError: 用例执行线程异常：
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/testbase/testcase.py", line 701, in _thread_run
    getattr(self._testcase, it)()
  File "/Users/Anker/qtaf_project/footestproj/footest/hello.py", line 35, in run_test
    device.connect_wifi('xxx', 'xxx')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qt4a/device.py", line 654, in connect_wifi
    if self._device_driver.connect_wifi(wifi_name, wifi_pass): return True
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qt4a/androiddriver/devicedriver.py", line 459, in connect_wifi
    return self._send_command('ConnectWifi', WifiName=wifi_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qt4a/androiddriver/devicedriver.py", line 372, in _send_command
    raise RuntimeError(result['Error'])
RuntimeError: java.lang.RuntimeException: ssid xxx not found
at com.test.androidspy.Device.connectWifi(Device.java:1111)
at com.test.androidspy.SpyHelper.onRecv(SpyHelper.java:647)
at com.test.androidspy.SocketServer$ServerBase.run(SocketServer.java:61)
at com.test.androidspy.SocketServer$LocalServerThread.run(SocketServer.java:136)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/testbase/testcase.py", line 703, in _thread_run
    self._testresult.exception('%s执行失败' % it)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/testbase/testresult.py", line 324, in exception
    self.log_record(EnumLogLevel.CRITICAL, msg, record, attachments)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/testbase/testresult.py", line 236, in log_record
    extra_record, extra_attachments = self._get_extra_fail_record_safe()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/testbase/testresult.py", line 295, in _get_extra_fail_record_safe
    raise RuntimeError("%s.get_extra_fail_record must return a 2 elements tuple" % class_path)
RuntimeError: HelloTest.get_extra_fail_record must return a 2 elements tuple

实际手机wifi列表是有xxx这个热点的，'xxx'我试了好几个wifi名字，都是这样的日志。

**Comment by drunkdream** [comment]
这个手机用`connect_wifi`接口有成功连接过wifi吗？

**Comment by xyd113** [comment]
> 这个手机用`connect_wifi`接口有成功连接过wifi吗？

没有

**Comment by drunkdream** [comment]
麻烦发下完整的`logcat`日志

**Comment by drunkdream** [comment]
设备是`root`过的还是`非root`的？

**Comment by xyd113** [comment]
非root的
