### ISSUE TITLE
pm clear命令可以清除数据提示权限问题

### ISSUE THREAD

**Issue by 812865052** [Tencent/QT4A#44]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhanghuiping/.pyenv/versions/3.6.2/envs/ui-3.6.2/lib/python3.6/site-packages/xy_hotlib/kwbase/suite/runner.py", line 148, in run
    self.case_runner.run(configs, options, cfg_module, vsaves, locks)
  File "/Users/zhanghuiping/.pyenv/versions/3.6.2/envs/ui-3.6.2/lib/python3.6/site-packages/xy_hotlib/kwbase/suite/runner.py", line 105, in run
    self.run_stage(instance, 'case_teardown')
  File "/Users/zhanghuiping/.pyenv/versions/3.6.2/envs/ui-3.6.2/lib/python3.6/site-packages/xy_hotlib/kwbase/suite/runner.py", line 48, in run_stage
    getattr(instance, stagename, lambda : 1)()
  File "./cases/InvestAppUITest/Android/atopdemo.py", line 75, in case_teardown
    self.release_app()
  File "/Users/zhanghuiping/.pyenv/versions/3.6.2/envs/ui-3.6.2/lib/python3.6/site-packages/jsonrpc_requests/jsonrpc.py", line 130, in __call__
    return self.__request_method(self.__method_name, args, kwargs)
  File "/Users/zhanghuiping/.pyenv/versions/3.6.2/envs/ui-3.6.2/lib/python3.6/site-packages/xy_hotlib/kwbase/suite/base.py", line 41, in __method
    self._run_step(self.__library, method_name, kwargs)
  File "/Users/zhanghuiping/.pyenv/versions/3.6.2/envs/ui-3.6.2/lib/python3.6/site-packages/xy_hotlib/kwbase/suite/base.py", line 44, in _run_step
    getattr(library, method_name)(**kwargs)
  File "/Users/zhanghuiping/.pyenv/versions/3.6.2/envs/ui-3.6.2/lib/python3.6/site-packages/xy_hotlib/kwbase/meta.py", line 59, in _parse_template
    return func(self, *args, **kwargs)
  File "./xy_buzlib/AppUi/InvestApp/Android/AndroidLibBase.py", line 75, in release_app
    self.app._release()
  File "./xy_buzlib/AppUi/InvestApp/Android/AppBase.py", line 53, in _release
    self.device.clear_data(self.package_name)  # 清除包数据
  File "/Users/zhanghuiping/.pyenv/versions/3.6.2/envs/ui-3.6.2/lib/python3.6/site-packages/qt4a/device.py", line 810, in clear_data
    return 'Success' in self.run_as(package_name, cmdline)
  File "/Users/zhanghuiping/.pyenv/versions/3.6.2/envs/ui-3.6.2/lib/python3.6/site-packages/qt4a/device.py", line 302, in run_as
    return self.adb.run_as(package_name, cmd, **kwargs)
  File "/Users/zhanghuiping/.pyenv/versions/3.6.2/envs/ui-3.6.2/lib/python3.6/site-packages/qt4a/androiddriver/adb.py", line 1360, in run_as
    raise PermissionError('run %s as %s failed' % (cmdline, package_name))
qt4a.androiddriver.util.PermissionError: run pm clear com.yingzt.invest as com.yingzt.invest failed

**Comment by codeskyblue** [comment]
Oppo手机会遇到权限问题
https://codeantenna.com/a/KSWtMSMczf

改一下开发者选项，禁用到权限监控就可以了
