### ISSUE TITLE
run-as无权限时，重打包之后还是无法访问目录

### ISSUE THREAD

**Issue by jeannedai** [Tencent/QT4A#45]
adb shell
shell@HWPLK:/ $ run-as com.tencent.mobileqq ls /data/data/com.tencent.mobileqq/files
m.tencent.mobileqq ls /data/data/com.tencent.mobileqq/files                   <
run-as: Could not set capabilities: Operation not permitted

![image](https://user-images.githubusercontent.com/46986275/61784494-60fd6200-ae3c-11e9-9d0b-df29685a6637.png)

**Comment by drunkdream** [comment]
有完整的报错堆栈吗？

**Comment by jeannedai** [comment]
已发你邮箱，请查收，谢谢

**Comment by drunkdream** [comment]
```
08-01 12:04:53.790 W/System.err(26747): java.io.IOException: open failed: EACCES (Permission denied)
08-01 12:04:53.791 W/System.err(26747): 	at java.io.File.createNewFile(File.java:942)
08-01 12:04:53.791 W/System.err(26747): 	at com.test.androidspy.inject.CmdExecutor.writeToFile(CmdExecuteActivity.java:74)
08-01 12:04:53.791 W/System.err(26747): 	at com.test.androidspy.inject.CmdExecutor.run(CmdExecuteActivity.java:172)
08-01 12:04:53.791 W/System.err(26747): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
08-01 12:04:53.791 W/System.err(26747): 	at libcore.io.Posix.open(Native Method)
08-01 12:04:53.791 W/System.err(26747): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
08-01 12:04:53.791 W/System.err(26747): 	at java.io.File.createNewFile(File.java:935)
08-01 12:04:53.791 W/System.err(26747): 	... 2 more
```
定位到是向`sdcard`中写文件报错导致的，设备为`华为荣耀7`，Android版本为`6.0`

@hqlian007 麻烦看下这个问题

**Comment by jeannedai** [comment]
在手机->设置->应用管理->QQ->权限->开启存储权限，之后就无此问题。
