### ISSUE TITLE
执行demo工程的示例脚本提示超时

### ISSUE THREAD

**Issue by xiaobin198734** [Tencent/QT4A#55]
### 机器信息及版本
ViVo X7Plus   安卓版本：5.1.1
QT4A版本：2.2.44

### 以下是错误信息详情：

步骤1: 1、登录Android demo
RESOURCE: acquire resource (res_type:android, res_group:None, condition:{}) successfully
c402489(vivo X7Plus arm64-v8a Android 5.1.1)
ENVIRONMENT: 申请 Android 设备成功：vivo X7Plus(c402489)
INFO: device=c402489(vivo X7Plus arm64-v8a Android 5.1.1)
2019-09-04 11:45:26,193 19312 执行shellc402489 sh /data/local/tmp/qt4a/SpyHelper.sh runServer "com.test.androidspy" TimeoutError(u'Execute timeout',)
Traceback (most recent call last):
  File "E:\QT4ADemoProj-master\qt4a\androiddriver\adbclient.py", line 229, in call
    ret = method(*args, **kwds)
  File "E:\QT4ADemoProj-master\qt4a\androiddriver\adbclient.py", line 353, in shell
    result = ADBPopen(self._sock, timeout=kwds['timeout']).communicate()
  File "E:\QT4ADemoProj-master\qt4a\androiddriver\adbclient.py", line 186, in communicate
    if self._running: raise TimeoutError('Execute timeout')
TimeoutError: Execute timeout
2019-09-04 11:45:26,196 19312 Exec adb shell failed: Run cmd shell c402489 sh /data/local/tmp/qt4a/SpyHelper.sh runServer "com.test.androidspy" failed
Traceback (most recent call last):
  File "E:\QT4ADemoProj-master\qt4a\androiddriver\adb.py", line 281, in run_adb_cmd
    cmd, *args, sync=sync, timeout=timeout, **kwargs)
  File "E:\QT4ADemoProj-master\qt4a\androiddriver\adb.py", line 202, in run_adb_cmd
    return self._adb_client.call(cmd, self._device_name, *args, sync=sync, retry_count=1, timeout=timeout)
  File "E:\QT4ADemoProj-master\qt4a\androiddriver\adbclient.py", line 266, in call
    if ret == None: raise TimeoutError(u'Run cmd %s %s failed' % (cmd, ' '.join(args)))
TimeoutError: Run cmd shell c402489 sh /data/local/tmp/qt4a/SpyHelper.sh runServer "com.test.androidspy" failed
CRITICAL: run_test执行失败
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\testbase\testcase.py", line 701, in _thread_run
    getattr(self._testcase, it)()
  File "demotest\hello.py", line 25, in run_test
    app = DemoApp(device)
  File "E:\QT4ADemoProj-master\demolib\demoapp.py", line 19, in __init__
    super(DemoApp, self).__init__(self.package_name, device)  #第一个参数传入主进程名，在demo app中，主进程名和包名相同
  File "E:\QT4ADemoProj-master\qt4a\androidapp.py", line 56, in __init__
    self._device.wake_screen()  # 唤醒屏幕
  File "E:\QT4ADemoProj-master\qt4a\device.py", line 751, in wake_screen
    return self._device_driver.wake_screen(wake)
  File "E:\QT4ADemoProj-master\qt4a\androiddriver\devicedriver.py", line 534, in wake_screen
    self.send_key(KeyCode.KEYCODE_POWER)
  File "E:\QT4ADemoProj-master\qt4a\androiddriver\devicedriver.py", line 616, in send_key
    return self._send_command('SendKey', Keys=keys)
  File "E:\QT4ADemoProj-master\qt4a\androiddriver\devicedriver.py", line 366, in _send_command
    result = self.client.send_command(cmd_type, **kwds)
  File "E:\QT4ADemoProj-master\qt4a\androiddriver\devicedriver.py", line 92, in client
    self._client = self.run_server()
  File "E:\QT4ADemoProj-master\qt4a\androiddriver\devicedriver.py", line 349, in run_server
    ret = self._run_server(server_name)
  File "E:\QT4ADemoProj-master\qt4a\androiddriver\devicedriver.py", line 302, in _run_server
    ret = self.run_driver_cmd('runServer', server_name, root=self.adb.is_rooted(), retry_count=1, timeout=10)
  File "E:\QT4ADemoProj-master\qt4a\androiddriver\devicedriver.py", line 71, in run_driver_cmd
    raise QT4ADriverNotInstalled('Please install QT4A driver first')
QT4ADriverNotInstalled: Please install QT4A driver first

   c402489的截图:E:\QT4ADemoProj-master\HelloTest_c402489_1567568726.2.png
INFO: logcat日志
   设备:c402489:E:\QT4ADemoProj-master\HelloTest_c402489_1567568726.log
INFO: QT4A日志
   qt4a_HelloTest_1567568726.log:E:\QT4ADemoProj-master\qt4a_HelloTest_1567568726.log
INFO: 释放设备资源
INFO: 释放设备资源

### logcat信息
D/WorkerThreadMonitor(26407): Kill MSF check result[ senderSize:0,sendInterval:6845965,receiveInterval=6845963,addCmdCount=0

D/DataFormatter( 3403): Special bytes : 0

D/DataUsageService( 3403): NetSpeed 0K/s 

D/AndroidRuntime(16419): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<

D/AndroidRuntime(16419): CheckJNI is OFF

D/AndroidRuntime(16419): Calling main entry com.test.androidspy.SpyHelper

I/HelperUtil(16419): MainLoop is Looper (main, tid 1) {184d9e9c}

D/idmap   (16436): error: no read access to /vendor/overlay: No such file or directory

I/HelperUtil(16419): dexloaderPath=/data/local/tmp/qt4a/libdexloader64.so

W/System.err(16419): java.lang.reflect.InvocationTargetException

W/System.err(16419): 	at java.lang.reflect.Method.invoke(Native Method)

W/System.err(16419): 	at java.lang.reflect.Method.invoke(Method.java:372)

W/System.err(16419): 	at com.test.androidspy.HelperUtil.setsid(HelperUtil.java:1353)

W/System.err(16419): 	at com.test.androidspy.SpyHelper.run(SpyHelper.java:116)

W/System.err(16419): 	at com.test.androidspy.SpyHelper.main(SpyHelper.java:98)

W/System.err(16419): 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)

W/System.err(16419): 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)

W/System.err(16419): Caused by: android.system.ErrnoException: setsid failed: EPERM (Operation not permitted)

W/System.err(16419): 	at libcore.io.Posix.setsid(Native Method)

W/System.err(16419): 	... 7 more

I/System.out(16419): service com.test.androidspy start

W/System.err(16419): java.io.IOException: Operation not permitted

W/System.err(16419): 	at android.net.LocalSocketImpl.bindLocal(Native Method)

W/System.err(16419): 	at android.net.LocalSocketImpl.bind(LocalSocketImpl.java:309)

W/System.err(16419): 	at android.net.LocalServerSocket.<init>(LocalServerSocket.java:48)

W/System.err(16419): 	at com.test.androidspy.SocketServer.run2(SocketServer.java:184)

W/System.err(16419): 	at com.test.androidspy.SocketServer.run(SocketServer.java:203)

W/System.err(16419): 	at com.test.androidspy.SpyHelper.run(SpyHelper.java:146)

W/System.err(16419): 	at com.test.androidspy.SpyHelper.main(SpyHelper.java:98)

W/System.err(16419): 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)

W/System.err(16419): 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)

I/art     (16419): System.exit called, status: 0

I/AndroidRuntime(16419): VM exiting with result code 0.

D/DataFormatter( 3403): Special bytes : 0

D/DataUsageService( 3403): NetSpeed 0K/s 

D/VPS     ( 1418): permission=com.bbk.iqoo.logsystem.permission.READ_DATA; It's VivoPermissionType.LAST, then PERMISSION_GRANTED!

**Comment by drunkdream** [comment]
> QT4ADriverNotInstalled: Please install QT4A driver first

请先使用`qt4a-manage install-driver`命令拷贝测试桩到手机
