### ISSUE TITLE
应用重打包后运行Crash

### ISSUE THREAD

**Issue by drunkdream** [Tencent/QT4A#72]
```
10-28 22:40:33.848  2146  2336 E XgStat  : java.lang.VerifyError: Verifier rejected class okio.AsyncTimeout$Watchdog: void okio.AsyncTimeout$Watchdog.run() failed to verify: void okio.AsyncTimeout$Watchdog.run(): [0x18] expected to be within a catch-all for an instruction where a monitor is held (declaration of 'okio.AsyncTimeout$Watchdog' appears in /data/app/com.tencent.karaoke-1/base.apk)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okio.AsyncTimeout$Companion.scheduleTimeout(Unknown Source)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okio.AsyncTimeout$Companion.access$scheduleTimeout(Unknown Source)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okio.AsyncTimeout.enter(Unknown Source)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okhttp3.internal.framed.FramedStream$FramedDataSink.emitDataFrame(FramedStream.java:499)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okhttp3.internal.framed.FramedStream$FramedDataSink.close(FramedStream.java:545)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okio.RealBufferedSink.close(Unknown Source)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:48)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okhttp3.RealCall.access$100(RealCall.java:33)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
10-28 22:40:33.848  2146  2336 E XgStat  : 	at java.lang.Thread.run(Thread.java:761)
10-28 22:40:33.848  2146  2336 D XgStat  : [OkHttp Dispatcher(1109): ProGuard:145] - Call the original uncaught exception handler.
```

**Comment by drunkdream** [comment]
已修复#71
