### ISSUE TITLE
获取logcat线程报错

### ISSUE THREAD

**Issue by c373760488** [Tencent/QT4A#98]
Python: 3.7.4
qtaf: 5.4.35
qt4a: 2.2.71
手机: sony z3
步骤：
关闭微信进程
打开微信（大概就在这里报错了）

```
2020-03-25 17:54:10,564 123145487785984 thread Thread-2 exit
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/qt4a/androiddriver/util.py", line 537, in run
    return threading.Thread.run(self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/qt4a/androiddriver/adb.py", line 589, in _logcat_thread_func
    init_process, item['pid'])
TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'
```
部分日志信息，希望有所帮助。。。
```
[system_server(3489)] [2020-03-25 17:46:11.053] D/BluetoothManagerService(3536): Message: 20
[system_server(3489)] [2020-03-25 17:46:11.053] D/BluetoothManagerService(3536): Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@a2eadc5:true
[com.tencent.mm:toolsmp(30533)] [2020-03-25 17:46:11.072] E/libEGL(30973): validate_display:255 error 3008 (EGL_BAD_DISPLAY)
[com.tencent.mm:toolsmp(30533)] [2020-03-25 17:46:11.073] I/Adreno-EGL(30973): <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (I741a3d36ca)
[com.tencent.mm:toolsmp(30533)] [2020-03-25 17:46:11.073] I/Adreno-EGL(30973): OpenGL ES Shader Compiler Version: E031.29.00.00
[com.tencent.mm:toolsmp(30533)] [2020-03-25 17:46:11.073] I/Adreno-EGL(30973): Build Date: 04/04/16 Mon
[com.tencent.mm:toolsmp(30533)] [2020-03-25 17:46:11.073] I/Adreno-EGL(30973): Local Branch: mybranch19053788
[com.tencent.mm:toolsmp(30533)] [2020-03-25 17:46:11.073] I/Adreno-EGL(30973): Remote Branch: quic/LA.BF.1.1.3_rb1.12
[com.tencent.mm:toolsmp(30533)] [2020-03-25 17:46:11.073] I/Adreno-EGL(30973): Local Patches: NONE
[com.tencent.mm:toolsmp(30533)] [2020-03-25 17:46:11.073] I/Adreno-EGL(30973): Reconstruct Branch: NOTHING
[system_server(3489)] [2020-03-25 17:46:11.180] D/ConnectivityService(5126): listenForNetwork for Listen from uid/pid:10243/30533 for NetworkRequest [ id=170, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
[com.tencent.mm:toolsmp(30533)] [2020-03-25 17:46:11.231] W/VideoCapabilities(30973): Unrecognized profile 2130706433 for video/avc
[com.tencent.mm:toolsmp(30533)] [2020-03-25 17:46:11.246] W/AudioCapabilities(30973): Unsupported mime audio/alac
[com.tencent.mm:toolsmp(30533)] [2020-03-25 17:46:11.247] W/AudioCapabilities(30973): Unsupported mime audio/dsd
[com.tencent.mm:toolsmp(30533)] [2020-03-25 17:46:11.254] W/VideoCapabilities(30973): Unsupported mime video/divx
[com.tencent.mm:toolsmp(30533)] [2020-03-25 17:46:11.257] W/VideoCapabilities(30973): Unsupported mime video/divx311
[com.tencent.mm:toolsmp(30533)] [2020-03-25 17:46:11.259] W/VideoCapabilities(30973): Unsupported mime video/divx4
[com.tencent.mm:toolsmp(30533)] [2020-03-25 17:46:11.267] W/VideoCapabilities(30973): Unsupported mime video/mp4v-esdp
[com.tencent.mm:toolsmp(30533)] [2020-03-25 17:46:11.280] I/VideoCapabilities(30973): Unsupported profile 4 for video/mp4v-es
[com.tencent.mm:toolsmp(30533)] [2020-03-25 17:46:11.285] D/cr_MediaCodecUtil(30973): [MediaCodecUtil.java:645] Found target encoder for mime video/avc : OMX.qcom.video.encoder.avc
[com.tencent.mm:push(29586)] [2020-03-25 17:46:11.493] W/art(30979): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[46,tid=30979,Native,Thread*=0x8bfee700,peer=0x1336c0a0,"mars::30979"]
[com.tencent.mm:push(29586)] [2020-03-25 17:46:11.534] W/art(30974): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[45,tid=30974,Native,Thread*=0x8d304f00,peer=0x13362100,"mars::30974"]
[ps(31006)] [2020-03-25 17:46:11.753] I/ps(31006): type=1400 audit(0.0:60607): avc: denied { getattr } for path="/proc/230" dev="proc" ino=9405 scontext=u:r:shell:s0 tcontext=u:r:logd:s0 tclass=dir permissive=1 ppid=13521 pcomm="adbd" tgid=13521 tgcomm="adbd"
[ps(31052)] [2020-03-25 17:46:12.873] I/ps(31052): type=1400 audit(0.0:60622): avc: denied { getattr } for path="/proc/230" dev="proc" ino=9405 scontext=u:r:shell:s0 tcontext=u:r:logd:s0 tclass=dir permissive=1 ppid=13521 pcomm="adbd" tgid=13521 tgcomm="adbd"
[com.google.android.gms.persistent(5538)] [2020-03-25 17:46:13.384] D/Uploader(25367): Network request failed class java.net.SocketTimeoutException(failed to connect to play.googleapis.com/216.58.200.42 (port 443) after 60000ms: isConnected failed: ETIMEDOUT (Connection timed out))
[com.tencent.mm(29485)] [2020-03-25 17:46:13.503] D/skia(29534): --- SkImageDecoder::Factory returned null
[com.tencent.mm(29485)] [2020-03-25 17:46:13.548] D/skia(29534): --- SkImageDecoder::Factory returned null
[com.tencent.mm:push(29586)] [2020-03-25 17:46:13.944] W/art(31109): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[47,tid=31109,Native,Thread*=0x8d304500,peer=0x133d4100,"mars::31109"]
[com.tencent.mm:push(29586)] [2020-03-25 17:46:14.127] W/art(31108): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[45,tid=31108,Native,Thread*=0x8bfefb00,peer=0x13362160,"mars::31108"]
[com.test.androidspy:service(30057)] [2020-03-25 17:46:14.298] W/ContextImpl(31142): Unable to create files subdir files
[com.test.androidspy:service(30057)] [2020-03-25 17:46:15.340] W/ContextImpl(31142): Unable to create files subdir files
[com.test.androidspy:service(30057)] [2020-03-25 17:46:16.371] W/ContextImpl(31142): Unable to create files subdir files
```

**Comment by drunkdream** [comment]
#107 已修复
